future: true
permalink: /:title/
url: http://LuyuanLi97.github.io
name: LuyuanLi97
author: Luyuan Li
qq: yourqq
email: lily35@mail2.sysu.edu.cn

duoshuo: yourname
beian:
cnzz:
weibo:
github: yourID
about: "这里是LuyuanLi97的个人博客，创建于2018年。"

safe: true
paginate: 20
