future: true
permalink: /:title/
url: http://LuyuanLi97.github.io
name: LuyuanLi97
author: Luyuan Li
qq: 
email: lily35@mail2.sysu.edu.cn

duoshuo: Luyuan Li
beian:
cnzz:
weibo:
github: github.com/LuyuanLi97
about: "这里是LuyuanLi97的个人博客，创建于2018年。"

safe: true
paginate: 20
